name: test

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: bahmutov/npm-install@v1
      - run: yarn type
      - run: yarn lint
      - name: cache request
        uses: actions/cache@v2
        with:
          path: |
            .cache
          key: ${{ hashFiles('builder/pokeapi/**') }}
      - run: ls .cache
      - run: yarn build:pages
      - uses: crazy-max/ghaction-github-pages@v2
        if: success() && github.ref == 'refs/heads/master'
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN_GH_PAGES }}
