name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: bahmutov/npm-install@v1
      - run: yarn type
      - run: yarn lint
      - name: cache request
        uses: actions/cache@v2
        with:
        path: |
          .cache
        key: static
      - run: yarn build:pages
